version: '3.6'

services:
  main:
    container_name: main
    build:
      context: .
      target: ${ENVIRONMENT}
    volumes:
      - .:/usr/src/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

    command: npm run start:dev
    env_file:
      - .env.${ENVIRONMENT}
